[build]
  publish = "dist"
  command = "pip install -r requirements-netlify.txt && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_BACKEND_URL = "https://truthful.onrender.com"
  PIP_NO_DEPS = "false"

[context.deploy-preview.environment]
  VITE_BACKEND_URL = "https://truthful.onrender.com"
  PIP_NO_DEPS = "false"

[build.environment]
  PYTHON_VERSION = "3.10"
  NODE_VERSION = "18"
  PIP_NO_DEPS = "false"