services:
  - type: web
    name: truthful-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: SKELETON_MODEL_PATH
        value: /var/models/skeleton_model_v4.pt
      - key: USE_SKELETON_MODEL
        value: True
      - key: SKELETON_FUSION_WEIGHT
        value: 0.6
      - key: SKELETON_DISTANCE_METHOD
        value: mahalanobis